export const LendingMarketABI = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },

  // ── Custom Errors ──────────────────────────────────────────
  { inputs: [], name: "AmountExceedsLimit",   type: "error" },
  { inputs: [], name: "AmountMismatch",       type: "error" },
  { inputs: [], name: "AskNotOpen",           type: "error" },
  { inputs: [], name: "BidNotOpen",           type: "error" },
  { inputs: [], name: "CannotLendToYourself", type: "error" },
  { inputs: [], name: "CurrencyMismatch",     type: "error" },
  { inputs: [], name: "DeadlineNotPassed",    type: "error" },
  { inputs: [], name: "DealNotActive",        type: "error" },
  { inputs: [], name: "DurationExceedsLimit", type: "error" },
  { inputs: [], name: "InsufficientRepayment",type: "error" },
  { inputs: [], name: "InvalidAmount",        type: "error" },
  { inputs: [], name: "InvalidDuration",      type: "error" },
  { inputs: [], name: "InvalidInterestRate",  type: "error" },
  { inputs: [], name: "NotBorrower",          type: "error" },
  { inputs: [], name: "NotYourOrder",         type: "error" },
  { inputs: [], name: "OrderNotOpen",         type: "error" },
  { inputs: [], name: "RateExceedsLimit",     type: "error" },
  { inputs: [], name: "ReentrantCall",        type: "error" },
  { inputs: [], name: "TransferFailed",       type: "error" },
  { inputs: [], name: "WrongFundingAmount",   type: "error" },

  // ── Events ─────────────────────────────────────────────────
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: "uint256", name: "orderId",  type: "uint256" },
      { indexed: true,  internalType: "address", name: "borrower", type: "address" },
    ],
    name: "AskCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: "uint256", name: "orderId",  type: "uint256" },
      { indexed: true,  internalType: "address", name: "borrower", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount",   type: "uint256" },
      { indexed: false, internalType: "string",  name: "currency", type: "string"  },
    ],
    name: "AskPosted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: "uint256", name: "orderId", type: "uint256" },
      { indexed: true,  internalType: "address", name: "lender",  type: "address" },
    ],
    name: "BidCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: "uint256", name: "orderId",      type: "uint256" },
      { indexed: true,  internalType: "address", name: "lender",       type: "address" },
      { indexed: false, internalType: "uint256", name: "amount",       type: "uint256" },
      { indexed: false, internalType: "string",  name: "currency",     type: "string"  },
      { indexed: false, internalType: "uint256", name: "interestRate", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "duration",     type: "uint256" },
    ],
    name: "BidPosted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: "uint256", name: "dealId",       type: "uint256" },
      { indexed: true,  internalType: "uint256", name: "bidId",        type: "uint256" },
      { indexed: true,  internalType: "uint256", name: "askId",        type: "uint256" },
      { indexed: false, internalType: "address", name: "borrower",     type: "address" },
      { indexed: false, internalType: "address", name: "lender",       type: "address" },
      { indexed: false, internalType: "uint256", name: "amount",       type: "uint256" },
      { indexed: false, internalType: "string",  name: "currency",     type: "string"  },
      { indexed: false, internalType: "uint256", name: "interestRate", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "duration",     type: "uint256" },
      { indexed: false, internalType: "uint256", name: "deadline",     type: "uint256" },
      { indexed: false, internalType: "uint256", name: "repaymentDue", type: "uint256" },
    ],
    name: "DealMatched",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "dealId",   type: "uint256" },
      { indexed: true, internalType: "address", name: "borrower", type: "address" },
      { indexed: true, internalType: "address", name: "lender",   type: "address" },
    ],
    name: "LoanDefaulted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true,  internalType: "uint256", name: "dealId",   type: "uint256" },
      { indexed: true,  internalType: "address", name: "borrower", type: "address" },
      { indexed: true,  internalType: "address", name: "lender",   type: "address" },
      { indexed: false, internalType: "bool",    name: "onTime",   type: "bool"    },
    ],
    name: "LoanRepaid",
    type: "event",
  },

  // ── View: Constants ────────────────────────────────────────
  {
    inputs: [],
    name: "MAX_AMOUNT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_DURATION",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_RATE",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },

  // ── Write Functions ────────────────────────────────────────
  {
    inputs: [
      { internalType: "uint256", name: "bidId", type: "uint256" },
      { internalType: "uint256", name: "askId", type: "uint256" },
    ],
    name: "acceptAsk",
    outputs: [{ internalType: "uint256", name: "dealId", type: "uint256" }],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "askId", type: "uint256" }],
    name: "cancelAsk",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "bidId", type: "uint256" }],
    name: "cancelBid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "dealId", type: "uint256" }],
    name: "markDefault",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount",   type: "uint256" },
      { internalType: "string",  name: "currency", type: "string"  },
    ],
    name: "postAsk",
    outputs: [{ internalType: "uint256", name: "askId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "amount",       type: "uint256" },
      { internalType: "string",  name: "currency",     type: "string"  },
      { internalType: "uint256", name: "interestRate", type: "uint256" },
      { internalType: "uint256", name: "duration",     type: "uint256" },
    ],
    name: "postBid",
    outputs: [{ internalType: "uint256", name: "bidId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "dealId", type: "uint256" }],
    name: "repayLoan",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },

  // ── View: State ────────────────────────────────────────────
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "asks",
    outputs: [
      { internalType: "uint256",                       name: "id",        type: "uint256" },
      { internalType: "address",                       name: "borrower",  type: "address" },
      { internalType: "uint256",                       name: "amount",    type: "uint256" },
      { internalType: "string",                        name: "currency",  type: "string"  },
      { internalType: "enum LendingMarket.OrderStatus",name: "status",    type: "uint8"   },
      { internalType: "uint256",                       name: "createdAt", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "bids",
    outputs: [
      { internalType: "uint256",                       name: "id",           type: "uint256" },
      { internalType: "address",                       name: "lender",       type: "address" },
      { internalType: "uint256",                       name: "amount",       type: "uint256" },
      { internalType: "string",                        name: "currency",     type: "string"  },
      { internalType: "uint256",                       name: "interestRate", type: "uint256" },
      { internalType: "uint256",                       name: "duration",     type: "uint256" },
      { internalType: "enum LendingMarket.OrderStatus",name: "status",       type: "uint8"   },
      { internalType: "uint256",                       name: "createdAt",    type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "deals",
    outputs: [
      { internalType: "uint256", name: "id",           type: "uint256" },
      { internalType: "uint256", name: "bidId",        type: "uint256" },
      { internalType: "uint256", name: "askId",        type: "uint256" },
      { internalType: "address", name: "borrower",     type: "address" },
      { internalType: "address", name: "lender",       type: "address" },
      { internalType: "uint256", name: "amount",       type: "uint256" },
      { internalType: "string",  name: "currency",     type: "string"  },
      { internalType: "uint256", name: "interestRate", type: "uint256" },
      { internalType: "uint256", name: "duration",     type: "uint256" },
      { internalType: "uint256", name: "deadline",     type: "uint256" },
      { internalType: "uint256", name: "repaymentDue", type: "uint256" },
      { internalType: "bool",    name: "repaidOnTime", type: "bool"    },
      { internalType: "bool",    name: "isActive",     type: "bool"    },
      { internalType: "uint256", name: "createdAt",    type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "dealId", type: "uint256" }],
    name: "getRepaymentDue",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalAsks",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalBids",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalDeals",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },

  // ── Receive ────────────────────────────────────────────────
  { stateMutability: "payable", type: "receive" },
] as const;
