export const LendingMarketABI = [
  { inputs: [], name: "AmountMismatch", type: "error" },
  { inputs: [], name: "AskNotOpen", type: "error" },
  { inputs: [], name: "BidNotOpen", type: "error" },
  { inputs: [], name: "CannotBorrowFromYourself", type: "error" },
  { inputs: [], name: "CurrencyMismatch", type: "error" },
  { inputs: [], name: "DeadlineNotPassed", type: "error" },
  { inputs: [], name: "DealNotActive", type: "error" },
  { inputs: [], name: "DurationMismatch", type: "error" },
  { inputs: [], name: "InterestRateMismatch", type: "error" },
  { inputs: [], name: "InvalidAmount", type: "error" },
  { inputs: [], name: "InvalidDuration", type: "error" },
  { inputs: [], name: "InvalidInterestRate", type: "error" },
  { inputs: [], name: "NotBorrower", type: "error" },
  { inputs: [], name: "NotYourOrder", type: "error" },
  { inputs: [], name: "OrderNotOpen", type: "error" },
  { inputs: [], name: "Unauthorized", type: "error" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "orderId", type: "uint256" },
      { indexed: true, internalType: "address", name: "lender", type: "address" },
    ],
    name: "AskCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "orderId", type: "uint256" },
      { indexed: true, internalType: "address", name: "lender", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "string", name: "currency", type: "string" },
      { indexed: false, internalType: "uint256", name: "interestRate", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "duration", type: "uint256" },
    ],
    name: "AskPosted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "orderId", type: "uint256" },
      { indexed: true, internalType: "address", name: "borrower", type: "address" },
    ],
    name: "BidCancelled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "orderId", type: "uint256" },
      { indexed: true, internalType: "address", name: "borrower", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "string", name: "currency", type: "string" },
      { indexed: false, internalType: "uint256", name: "interestRate", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "duration", type: "uint256" },
    ],
    name: "BidPosted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "dealId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "bidId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "askId", type: "uint256" },
      { indexed: false, internalType: "address", name: "borrower", type: "address" },
      { indexed: false, internalType: "address", name: "lender", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "string", name: "currency", type: "string" },
      { indexed: false, internalType: "uint256", name: "deadline", type: "uint256" },
    ],
    name: "DealMatched",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "dealId", type: "uint256" },
      { indexed: true, internalType: "address", name: "borrower", type: "address" },
      { indexed: true, internalType: "address", name: "lender", type: "address" },
    ],
    name: "LoanDefaulted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "dealId", type: "uint256" },
      { indexed: true, internalType: "address", name: "borrower", type: "address" },
      { indexed: true, internalType: "address", name: "lender", type: "address" },
      { indexed: false, internalType: "bool", name: "onTime", type: "bool" },
    ],
    name: "LoanRepaid",
    type: "event",
  },
] as const;
